### ISSUE TITLE
Support generating file that is not a module

### ISSUE THREAD

**Issue by mrdomino** [Yovach/next-public-ts#50]
https://github.com/vercel/next.js/issues/33863#issuecomment-1783841956

> > Hmm, somehow my sw.js file (generated from something like the ts you showed) is ending up with an `export` statement in it at the end that is tripping up my browser. Investigating... any ideas?
> > EDIT: Ah, `type: 'module'` in `serviceWorker.register` is probably it.
> 
> I'll fix the issue because sometimes, you don't need that and it includes unnecessary code

**Comment by Yovach** [comment]
I don't think that's possible to avoid the type `module` as we need to use `export type` in `sw.ts`.
If I configure `swc` to use non-module files, it crashes with
```
   × 'import', and 'export' cannot be used outside of module code
   ╭─[1:1]
 1 │ /// <reference lib="WebWorker" />
 2 │ export type {};
   · ──────
 3 │ declare let self: ServiceWorkerGlobalScope;
 4 │ 
 5 │ self.addEventListener("install", async () => {
```

**Comment by mrdomino** [comment]
What is the `export type` doing?

**Comment by Yovach** [comment]
The `export type {};` line is just a placeholder, otherwise Typescript cries

**Comment by Yovach** [comment]
Can I close the issue as the problem seems to have been resolved?

**Comment by mrdomino** [comment]
Sure. I would say not planned rather than resolved though.
