### ISSUE TITLE
Imports should be compiled out

### ISSUE THREAD

**Issue by mrdomino** [Yovach/next-public-ts#67]
I'd like to be able to import some code in `sw.ts` and have that code inlined in the resultant `sw.js`. Instead, the `import` statement is being passed through to the result, leading to an import error.

**Comment by Yovach** [comment]
Hi, `swc` doesn't support `bundling` (if not using [`spack`](https://swc.rs/docs/configuration/bundling)).

You can use `import` statement in `sw.js` by adding the file extension like the following : 

```javascript
// helpers.js
export function add(a, b) {
  return a + b;
}
```

```javascript
// sw.js
import { add } from "./helpers.js"
console.log(add(5, 10));
```

In your TypeScript files, you'll need to add the `.js` extension in imports

**Comment by mrdomino** [comment]
In that case I assume `helpers.js` also needs to be in public?

**Comment by Yovach** [comment]
Yes, `helpers.js` have to be in public

**Comment by Yovach** [comment]
Can I close the issue as the problem seems to have been resolved?

**Comment by mrdomino** [comment]
Sure, though as with the other one I'd say not-planned.
